version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      - run:
          name: install dependencies
          commands: |
           python3 -m venv venv
           .venv/bin/activate
      - run:
          name: run tests
          commands: |
           .venv/bin/activate
           pytest